### ISSUE TITLE
NDEBUG issue in v0.9.1

### ISSUE THREAD

**Issue by jupinet** [Derecho-Project/derecho#131]
My application was working with v0.9.
Following the README.md to upgrade to v0.9.1 with CMAKE_BUILD_TYPE=Release, changing the code for SubgroupInfo and p2p_send. My application can build but get crash in runtime.
Base on the error message, I saw that the issue comes from line 818 in SerializationSupport.hpp.
I tried to update CMakeList.txt with NDEBUG in CMAKE_BUILD_TYPE=Release and it works now.
I don't know the issue from my code or just missing the build options.
Please verify and fix it if needed.

**Comment by KenBirman** [comment]
jupinet, next time please post a small example that can trigger the bug, and exact details on the runtime environment and the exact error message.  But in fact I think this is very likely to be an issue Edward just pinned down and fixed, from your description.  Without details, we can only guess, but it does match the general "sound" of the issue Edward just resolved.

The thing to appreciate is this: think about code you might have written, something called "my amazing thing.cpp".  I run it with some kind of strange input and it crashes.

Well, bugs do happen.  But could you fix it just from me posting a report that "your amazing thing sometimes crashes at line 1234 in some_module.cpp"?  Probably not, right?  So that's our issue, too...

**Comment by jupinet** [comment]
KenBirman, my description may not clear in general because I assumed that Derecho's developers know SerializationSupport.hpp is Derecho's code.
I found the commit fixed that  bug [bugfix: release target lost -DNDEBUG (found by Xinzhe)](https://github.com/Derecho-Project/derecho/commit/ecd2806aec67a83b691070732f9667917bf36cb1)
Thanks for your help!
