### ISSUE TITLE
SMC always send max_smc_payload_size bytes no matter the real message size

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#172]
Can we make SMC more flexible to avoid wasting bandwidth by sending the padding data in the buffer? This allows us to set the smc_max_payload to a higher number for performance gains. Or, spindle's batching mechanism can compensate the overhead and make it not necessary?

**Comment by sagarjha** [comment]
Hi Weijia,

When we add the opportunistic sending mechanism from Spindle, we will not be able to send the exact amount of data as specified by the message size. This is because opportunistic send seeks to batch multiple messages together and since each message is present in a different slot, sending all of them in one RDMA write requires us to send the empty bytes as well.

Jonathan and I made the decision to use discrete ring buffer instead of a continuous one to keep the implementation simple. And as we know for small messages, the latency of RDMA write does not vary much with the message size.

**Comment by songweijia** [comment]
We have a per subgroup `max_smc_payload_size` setting to match the message size for each subgroup. We assume the variance of the message size in each subgroup is low. Therefore, the `max_smc_payload_size` can be set to a value close to the average message size to minimize the overhead.
