### ISSUE TITLE
Confusing comment

### ISSUE THREAD

**Issue by Panlichen** [Derecho-Project/derecho#185]
According to [this line](https://github.com/Derecho-Project/derecho/blob/002cf1bf3f/src/core/view_manager.cpp#L1843) and [this line](https://github.com/Derecho-Project/derecho/blob/002cf1bf3f/src/core/view_manager.cpp#L1865), the comments [here](https://github.com/Derecho-Project/derecho/blob/master/include/derecho/core/detail/multicast_group.hpp#L216) should be `The members of the shard`. This confused me a lot.

**Comment by etremel** [comment]
You're right about the comments being out-of-date; the members vector in `SubgroupSettings` contains only the members of "this node's shard" of the subgroup. I think the original intention was for there to be one `SubgroupSettings` per subgroup in the Group, but then we realized that each node only needed to know those settings for the single shard of the subgroup it was a member of, not the entire subgroup. So `MulticastGroup` has one `SubgroupSettings` per subgroup, but that `SubgroupSettings` only relates to the single shard of the subgroup that the local node is a member of, because each node can only be a member of one shard per subgroup. I can fix the comments to reflect this.
