### ISSUE TITLE
A minor issue of using std::move() on std::reference_wrapper.

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho#202]
@etremel, I find that [some of your code](https://github.com/Derecho-Project/derecho/blob/aff96e91874171b61610bd4939b0dedcb78ce619/src/core/rpc_manager.cpp#L164) uses `std::move()` on [`std::reference_wrapper`](https://en.cppreference.com/w/cpp/utility/functional/reference_wrapper) objects. Since std::reference_wrapper is CopyConstructible and does not support a move constructor from ANOTHER std::reference_wrapper, I'm wondering if we should remove the `std::move()` in that line (and similar lines like L166)?

**Comment by etremel** [comment]
Yes, you're right, there's no need to move a std::reference_wrapper, since moving it is exactly the same as copying it. I think when I wrote that code, I forgot that the results maps contained reference_wrappers, and just wrote the default boilerplate for "pop an object off a queue." (Normally, the std::move is necessary because std::queue doesn't have a "remove and return" operation, and accessing the front element will copy-assign it even if you're about to call pop() and delete it).
