### ISSUE TITLE
Small issue with make -jN

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho#55]
I get a warning `jobserver unavailable: using -j1.  Add '+' to parent make rule.` when I run `make -jN`. It still runs the command properly despite the warning. But it will be useful to get rid of the warning. Low priority for now.

**Comment by etremel** [comment]
This appears to be fixed as of the current Ubuntu version of CMake (3.10.2), since I no longer see this warning when building with `make -j8`. As documented [here](https://stackoverflow.com/questions/60702726/warning-jobserver-unavailable-using-j1-add-to-parent-make-rule), this warning occurs if a Makefile recursively calls make without using the magic $(MAKE) variable, so it must have been appearing because CMake was generating Makefiles that did not correctly use $(MAKE) to recurse into subfolders. Our current CMake setup no longer does this (all generated Makefiles use $(MAKE) rather than a bare make) so I think this is no longer an issue.
