### ISSUE TITLE
Make various max message sizes configurable per subgroup

### ISSUE THREAD

**Issue by sagarjha** [Derecho-Project/derecho#68]
Currently all subgroups have the same values for `max_msg_size` and `sst_max_msg_size`. If one needs to only send small messages in their application, they set `max_msg_size` and `sst_max_msg_size` to the same small value (typically up to tens of KBs). On the other hand, if one needs to also send very large messages (up to hundreds of MBs), they set `max_msg_size` to the large desired value and `sst_max_msg_size` to tens of KBs, so that they benefit from the specialized SST multicast for small messages. Every subgroup automatically supports the two protocols, one for large messages and one for small messages.
It is, however, reasonable to assume that one might want only some subgroups to send large messages. In that case, it might benefit us to separate these parameters between subgroups because then the subgroups that are only sending small messages do not need to allocate and maintain large chunks of memory. This falls back to our design of the memory management layer that allocates buffers and registers them with the NIC at initialization to speed up the critical path of message sends during common subgroup operations.

**Comment by songweijia** [comment]
Cool, this is the right choice!

**Comment by evantzhao** [comment]
When making a subview, you can specify a custom profile by the string name (case-insensitive), to be used in the subgroup. This custom profile must be specified in the CFG files; otherwise, an exception will be thrown. If you do not specify a profile when making  a subview, Derecho by default uses a profile named "DEFAULT". See below for more information.

With the addition of subgroup profiles, we have changed the format of how default subgroup properties (MAX_SMC_MSG_SIZE, etc, etc) are defined in the cfg files -- Please look at derecho-sample.cfg to see how these, and custom subgroup profiles, should be specified.
