### ISSUE TITLE
Race condition if the leader fails during a view change

### ISSUE THREAD

**Issue by etremel** [Derecho-Project/derecho#92]
When a new leader takes over, right now it simply waits for all rows to be wedged, but because of the way the ragged trim is propagated, this isn’t a strong enough barrier.  The new leader, L, should  

(a) suspect the old leader
(b) push the row
(c) wait until every non-suspected process considers L to be the leader
(d) compute the cleanup.  

In this (c) is the step we were missing.  The assumption is that an old leader, Q, is propagating a ragged trim and when it reaches P that trim will have a majority and should become stable.  But this is a race condition: P may be wedged already, and when L takes over, it could scan P’s ragged trim echo before P hears from Q.  L would then not necessarily learn of Q’s stable ragged trim and a message delivery bug can result, if Q had already acted on the ragged trim before it crashed.

**Comment by KenBirman** [comment]
In step (d) it is also important for the new leader to scan the SST, checking for proposals (view changes or ragged trim) made by a prior leader.  This should be done in reverse rank order by leader, so that if process L was leader, then process M, then N, and now O is taking over, O looks first for a proposal by N and if it finds one, adopts it.  Then only if there was no proposal by N, O would look for a proposal by M, and so forth.  O stops as soon as it finds one to adopt, and only computes a new ragged trim proposal if it didn't find a prior one.

Additionally, a prior view change proposal cannot be "modified".  So perhaps L when it was leader proposes some view change V'.  Now M takes over and wants to propose that because L has failed, L should be dropped.  It can't modify V' (if it discovers V').  Instead it proposes V',V" (two successive views).  Thus after K takeovers without a commit, we could be looking at K proposals: V',V", …. V''''

This rule is guaranteed to not suffer from partitioning bugs (split brain) even if the view proposals include some that add additional members.
